apiVersion: v1
kind: Service

metadata:
  name: ecommerce-backend

spec:

  type: {{ .Values.backend.service.type }}

  selector:
    app: ecommerce-backend

  ports:

    - protocol: TCP

      port: {{ .Values.backend.service.port }}

      targetPort: 5000
