apiVersion: v1
kind: Service

metadata:
  name: ecommerce-frontend

spec:

  type: {{ .Values.frontend.service.type }}

  selector:
    app: ecommerce-frontend

  ports:

    - protocol: TCP

      port: {{ .Values.frontend.service.port }}

      targetPort: 80
