apiVersion: v1
kind: Service

metadata:
  name: ecommerce-mysql

spec:

  type: {{ .Values.mysql.service.type }}

  selector:
    app: ecommerce-mysql

  ports:

    - protocol: TCP

      port: {{ .Values.mysql.service.port }}

      targetPort: 3306
