apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: ecommerce-eks
  region: ap-south-1

managedNodeGroups:

  - name: ecommerce-nodes

    instanceType: t3.small

    desiredCapacity: 1

    minSize: 1

    maxSize: 1

    volumeSize: 20

    labels:
      role: ecommerce-worker
