apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce-eks
  region: ap-south-1

managedNodeGroups:
  - name: ecommerce-m7i-nodes
    instanceType: m7i-flex.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    volumeType: gp3
